# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml
substitutions:
  _IMAGE_VERSION: 1.0.0
steps:
  - id: 'build'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/soma:latest'
      - '-t'
      - 'gcr.io/$PROJECT_ID/soma:${_IMAGE_VERSION}'
      - '-f'
      - '.docker/Dockerfile'
      - '--target'
      - 'prod'
      - '.'
  - id: "go_test"
    name: "gcr.io/cloud-builders/go"
    args: ["test","./..."]
    env: ["GOPATH=."]
  - id: "run"
    name: "gcr.io/cloud-builders/go"
    args: ["run","soma"]
    env: ["GOPATH=."]

images:
  - 'gcr.io/$PROJECT_ID/soma:latest'
  - 'gcr.io/$PROJECT_ID/soma:${_IMAGE_VERSION}'
tags: ['cloud-builders-community']