# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml
substitutions:
  _IMAGE_VERSION: 1.0.0
steps:
  - id: 'build'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/soma:latest'
      - '-t'
      - 'gcr.io/$PROJECT_ID/soma:${_IMAGE_VERSION}'
      - '-f'
      - '.docker/Dockerfile'
      - '.'
  - id: "test"
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'run'
      - 'gcr.io/$PROJECT_ID/soma'
      - 'go test'
  - id: "run"
    name: 'gcr.io/$PROJECT_ID/soma'

images:
  - 'gcr.io/$PROJECT_ID/soma:latest'
  - 'gcr.io/$PROJECT_ID/soma:${_IMAGE_VERSION}'
tags: ['cloud-builders-community']